### PR TITLE
"Fire style"

### PR DESCRIPTION
**Pull request by adamwong246**
for your approval, an additional setting "fire". Where "damage" causes slow damage and "destroy" just kills the power pole, "fire" will spawn a fire entity. This is done probabilistically and the threshold is exposed as a user setting.

### CODE REVIEW

**Comment by tburrows13** [comment]
Thanks very much for this, I really like the feature. I'm not so sure about the probability bit since the decision of which poles to check is already random, and the chances of a pole being picked are arranged before the pole loop. The dependence on the amount that the consumption is over the max-consumption is nice though, so I might keep that, and scrap the user-setting bit. It isn't clear to a user how changing that affects the fire chances anyway.

**Comment by adamwong246** [comment]
Feel free to tweak that formula, I pulled it out of thin air.

**Comment by tburrows13** [comment]
Hello! This contribution was made under LGPL-3.0, but I'm interested in moving PowerOverload to the MIT License. For this I need permission from all source code contributors, so are you happy to give permission for this change? Absolutely no worries if not, it isn't a big deal to me :)

(The reason it is currently LGPL is because I included some code from a different LGPL mod - Beltlayer. I've now got rid of that code so I'm otherwise free to change the license.)

**Comment by adamwong246** [comment]
Yes, MIT is just fine.

**Pull request merged**
